### ISSUE TITLE
run_make_database.py

### ISSUE THREAD

**Issue by jcastrolopes98** [hanyoseob/pytorch-UNET#1]
Hi! I'm trying to run the run_make_database.py script. I get the following output:

Traceback (most recent call last):

  File "<ipython-input-50-841c813a696a>", line 1, in <module>
    runfile('/home/user/Downloads/UNET/run_make_database.py', wdir='/home/user/Downloads/UNET')

  File "/usr/lib/python3/dist-packages/spyder_kernels/customize/spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "/usr/lib/python3/dist-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/user/Downloads/UNET/run_make_database.py", line 12, in <module>
    img_target = Image.open(os.path.join(dir_data, name_target))

  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 2809, in open
    fp = builtins.open(filename, "rb")

FileNotFoundError: [Errno 2] No such file or directory: '../../datasets/em/train-labels.tif'

Am I suppose to do something first?

Thank you.

**Comment by YanWanquan** [comment]
> 

Have you find out the dataset? Thanks
